version: '0.2'
ignorePaths:
  - .gitignore
  - .prettierignore
  - '*-lock.{yaml,json}'
  - /dist
  - .git/*/**
  - node_modules
dictionaryDefinitions: []
dictionaries: []
words:
  - corepack
  - endregion
  - Evaluatable
  - linkcode
  - nodenext
  - pnpm
  - quickfix
  - rfdc
  - tsbuild
  - unrs-resolver
  - VSIX
ignoreWords: []
import: []
